name: backend
description: A new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog: ^1.1.0
  postgres: ^3.5.9
  drift: ^2.20.0
  drift_postgres: ^1.3.1
  bcrypt: ^1.2.0
  mailer: ^6.6.0
  dart_jsonwebtoken: ^3.3.1

dev_dependencies:
  dart_frog_lint: ^0.1.0
  mocktail: ^1.0.3
  test: ^1.25.5
  drift_dev: ^2.20.0
  build_runner: ^2.4.9
